baseURL = 'https://yoyoxie0729.github.io'
languageCode = 'zh-cn'
title = "YHDEV's Cave"
theme = "terminal"
paginate = 5

[params]
contentTypeName = "posts"
themeColor = "green"
showMenuItems = 2
fullWidthTheme = false
centerTheme = true

[languages]
[languages.en]
title = "YHDEV's Cave"
subtitle = "A simple, retro theme for Hugo"
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "YHDEV's Cave"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "showcase"
name = "Showcase"
url = "/showcase"
